import { Inter } from "next/font/google";
import Script from 'next/script'
import "./globals.css";
import '../css/normalize.css' // @csstools/Normalize CSS 12.1.1
import '../css/bootstrap.min.css' // Bootstrap CSS 4.6.2


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" crossOrigin="anonymous" />
      </body>
    </html>
  );
}
